package wang.raye.springboot.model;

public class User {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.id
	 *
	 * @mbg.generated
	 */
	private Integer id;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.username
	 *
	 * @mbg.generated
	 */
	private String username;
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.psw
	 *
	 * @mbg.generated
	 */
	private String psw;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.id
	 *
	 * @return the value of user.id
	 *
	 * @mbg.generated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.id
	 *
	 * @param id
	 *            the value for user.id
	 *
	 * @mbg.generated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.username
	 *
	 * @return the value of user.username
	 *
	 * @mbg.generated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.username
	 *
	 * @param username
	 *            the value for user.username
	 *
	 * @mbg.generated
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.psw
	 *
	 * @return the value of user.psw
	 *
	 * @mbg.generated
	 */
	public String getPsw() {
		return psw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.psw
	 *
	 * @param psw
	 *            the value for user.psw
	 *
	 * @mbg.generated
	 */
	public void setPsw(String psw) {
		this.psw = psw == null ? null : psw.trim();
	}
}